---
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

- name: Set up development pre-reqs on a local machine
  hosts: dev
  become: yes

  tasks:
    - name: Make sure (empty) local repo structure exists
      become: no
      shell: mkdir -p ~/endaga-packages/dists/localdev/main/binary-amd64/

    - name: Make sure (empty) local repo Packages file exists
      become: no
      shell: touch ~/endaga-packages/dists/localdev/main/binary-amd64/Packages

    - include: base.yml

    - include: osmocom.yml

    - name: Add local repo (for local development)
      apt_repository: repo='deb file:/home/vagrant/endaga-packages localdev main' state=present update_cache=no

    - name: Set the local development repo to order 30
      shell: sudo mv /etc/apt/sources.list.d/file_home_vagrant_etagecom_packages.list /etc/apt/sources.list.d/30_file_home_vagrant_etagecom_packages.list || exit 0

    - name: Set the version preferences
      copy: src=files/endaga-preferences dest=/etc/apt/preferences.d/endaga-preferences


    - name: Install prereqs for FPM
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - ruby-dev
          - build-essential
          - libssl-dev

    - name: Setup FPM so we can build packages
      shell: gem install fpm

    - name: Setup build requirements for python packages
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - python3-babel
          - python3-dev
          - python3-setuptools

    - name: Get pip3 installer (not from debian repositories, uses ancient version)
      get_url:
        url: https://bootstrap.pypa.io/get-pip.py
        dest: /tmp/get-pip.py

    - name: Install pip
      command: python3 /tmp/get-pip.py

    - name: Setup requirements for building FS from source (needed to generate working python modules)
      apt: pkg={{ item }} state=present update_cache=no
      with_items:
          - libsqlite3-dev
          - devscripts
          - libsmpp34-dev
          - libesl-perl
          - autoconf

    - name: Setup requirements for building psycopg2 from source
      apt: pkg=libpq-dev state=present update_cache=no

