#!/usr/bin/env python3
#
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

"""A utility to view the local HLR contents.

Usage: ccm_hlr list
       ccm_hlr delete (<imsi> | --delete-all-subs)

Options:
       --delete-all-subs  Delete all subscribers from both DB and HLR (use
                          with caution, no confirmation required)
"""






import sys

import docopt

from ccm.common.crdt.base import PNCounter
from core.config_database import ConfigDB
from core.subscriber import subscriber


if __name__ == "__main__":
    args = docopt.docopt(__doc__)

    if args["list"]:
        for imsi, data in list(subscriber.get_subscriber_states().items()):
            bal = PNCounter.from_json(data["balance"]).value()
            sub_info = subscriber.get_subscribers(imsi)
            numbers = sub_info[0]["numbers"] if sub_info else "<none>"
            print("%s: balance = %d, numbers: %s" %
                  (imsi, bal, numbers))

    elif args["delete"]:
        if "--delete-all-subs" in args:
            for imsi in subscriber.get_subscriber_states():
                subscriber.delete_subscriber(imsi)
        else:
            subscriber.delete_subscriber(args["<imsi>"])
