#!/usr/bin/env python3

# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

import sys

from ccm.common import logger
from core.gprs import daemon


logger.notice('starting endaga-gprsd')
try:
    daemon.main()
except Exception as e:
    logger.error('gprsd died with: %s' % e)
    sys.exit(1)
logger.notice('stopping endaga-gprsd')
