#!/usr/bin/env python3

"""The client's primary server.

Handles commands sent by the cloud, incoming SMS, delivery receipts, subscriber
provisioning and parsing CDRs.

Receives CDRs from Freeswitch mod_xml_cdr and updates subscriber registry
accordingly.

Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant 
of patent rights can be found in the PATENTS file in the same directory.
"""

import core.federer

core.federer.app.run()
