#!/usr/bin/env python3

# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
# 
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant 
# of patent rights can be found in the PATENTS file in the same directory.

import argparse

from core import config_database

if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="CLI for ConfigDB.")
    parser.add_argument('--force', '-f', action='store_true',
                        help="Overwrite existing data.")
    args = parser.parse_args()

    config_database.set_defaults(force_replace=args.force)
