#!/usr/bin/env python
"""Writes the versions of the main installed packages into the ConfigDB.

This runs as a postinst for the endaga metapackage.  We'll later send this info
to the cloud during checkins.

Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant 
of patent rights can be found in the PATENTS file in the same directory.
"""

import envoy

from core.config_database import ConfigDB

#this should be moved to common and used in the bts classes directly
def get_version(package_name):
    """Runs dpkg-query to get package version info."""
    query = envoy.run("dpkg-query -W -f '${version}' %s" % package_name)
    result = query.std_out
    if 'dpkg-query' in result:
        # The result was probably "dpkg-query: no packages found matching
        # <package_name>" (an error).
        return ''
    return result


config_db = ConfigDB()
packages = [('endaga', ['endaga-openbts',
                        'endaga-osmocom']), 
            ('freeswitch', ['freeswitch']),
            ('gsm', ['openbts-public',
                     'osmocom-nitb']), 
            ('python-endaga-core', ['python-endaga-core']),
            ('python-gsm', ['python-openbts',
                            'python-osmocom']),
        ]
for package in packages:
    key = package[0]
    working_package_names = package[1]
    for name in working_package_names:
        res = get_version(name)
        if (res):
            print (key + ":" + res)
            key = '%s_version' % key
            config_db[key] = res
            break


