#!/usr/bin/python

"""
Copyright (c) 2016-present, Facebook, Inc.
All rights reserved.

This source code is licensed under the BSD-style license found in the
LICENSE file in the root directory of this source tree. An additional grant
of patent rights can be found in the PATENTS file in the same directory.

This migrates pre-0.7 style balance (integers) to CRDT-based representation.

Should be safe to run multiple times, as we'll ignore any balances that aren't
integers.
"""

import os
import psycopg2

from ccm.common import crdt
from core.subscriber.base import BaseSubscriber

PG_USER = os.environ.get('PG_USER', 'endaga')
PG_PASSWORD = os.environ.get('PG_PASSWORD', 'endaga')

conn = psycopg2.connect(host='localhost', database='endaga',
                user=PG_USER, password=PG_PASSWORD)

subs = {}
with conn:
    with conn.cursor() as cur:
        cur.execute("SELECT imsi, balance FROM subscribers")
        res = cur.fetchall()
        for item in res:
            imsi = item[0]
            try:
                balance = int(item[1])
            except ValueError:
                continue # already not an int, ignore
            subs[imsi] = balance
            print imsi, balance

        # We intentionally ignore balance here. The cloud already has
        # subscriber balance, so on the next checkin the states will be merged.
        # If we increment here, we'd wind up with doubling of balance.
        for imsi in subs:
            pn_bal = crdt.PNCounter()
            BaseSubscriber._set_balance(cur, imsi, pn_bal)
