#!/bin/sh
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

# Get rid of old server directives in lighttpd. This replaces inline and
# creates a backup copy of the file; if there is an existing backup file it is
# overwritten. We do this so we can control these settings in our own config
# file.

if [ -f /etc/lighttpd/lighttpd.conf ]; then
    sed -i.bak 's/^\(server.\(breakagelog\|reject-expect\|port\)\)/#\1/' /etc/lighttpd/lighttpd.conf
fi
