#!/bin/sh
# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

echo "This software depends on code that is licensed under AGPL";

read -r -p "Are you sure you want to install? [Y/n] " response
case "$response" in
    [yY][eE][sS]|[yY]|"") 
              exit
              ;;
    *)
              exit 1
              ;;
esac
