#!/bin/bash

# Copyright (c) 2016-present, Facebook, Inc.
# All rights reserved.
#
# This source code is licensed under the BSD-style license found in the
# LICENSE file in the root directory of this source tree. An additional grant
# of patent rights can be found in the PATENTS file in the same directory.

error_exit() {
    local message=$1

    echo "[FATAL] $message" 1>&2
    exit 1
}

sudo apt-get update -y

if [ $? != 0 ]; then
    error_exit "Couldn't update package repo."
fi

sudo apt-get install -y byobu nginx uwsgi python-pip python-dev libpq-dev git supervisor daemontools binutils libproj-dev gdal-bin

if [ $? != 0 ]; then
    error_exit "Couldn't install dependencies."
fi
